config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about'
  get 'welcome/dashboard'
  root :to => 'welcome#index'

  get '/users/:user_id/clients/new', :to => 'clients#new'

  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'devise/registrations#new'}

  get '/clients/:client_id/goals/new', :to => 'goals#new'
  get '/goals/:goal_id/steps/new', :to => 'steps#new'
  get '/steps/:step_id/messages/new', :to => 'messages#new'

  resources :clients
  resources :goals
  resources :steps
  resources :messages

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :client
  belongs_to :step
  validates :client, presence:{message: "Message must be associated with client"}
  validates :step, presence:{message: "Message must be associated a step"}

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show

  end

  # GET /messages/new
  def new
    @step = Step.find(params[:step_id])
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.step_id = params[:step_id]
    @message.client_id = Step.find(params[:step_id]).goal.client.id

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :date, :send_attempted, :send_successful, :step_id, :client_id)
    end
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <% if @client %>
    <%= hidden_field_tag :client_id, @client.id %>
  <% end %>
  <% if @step %>
    <%= hidden_field_tag :step_id, @step.id %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', message_path(@message) %>

app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Status</th>
      <th>Scheduled</th>
      <th>Send Attempted</th>
      <th>Send Successful</th>
      <th>Goal</th>
      <th>Client</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.status %></td>
        <td><%= message.by_when %></td>
        <td><%= message.send_attempted %></td>
        <td><%= message.send_successful %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to "New Message", "/steps/#{@step.id}/messages/new" %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', step_path(@step) %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scheduled For:</strong>
  <%= @message.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @message.send_attempted %>
</p>

<p>
  <strong>Sent?</strong>
  <%= @message.send_successful %>
</p>

<p>
  <strong>Step:</strong>
  <%= link_to "View Step", step_path(@message.step_id) %>
</p>

<p>
  <strong>Client:</strong>
  <%= link_to "View Client", client_path(@message.client_id) %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %>
<%= link_to 'Back', step_path(@message.step_id) %>