config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about'
  get 'welcome/dashboard'
  root :to => 'welcome#index'

  get '/users/:user_id/clients/new', :to => 'clients#new'

  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'devise/registrations#new'}

  get '/clients/:client_id/goals/new', :to => 'goals#new'
  get '/goals/:goal_id/steps/new', :to => 'steps#new'
  get '/steps/:step_id/messages/new', :to => 'messages#new'

  resources :clients
  resources :goals
  resources :steps
  resources :messages

end

app/models/client.rb
class Client < ActiveRecord::Base
  validates_presence_of :name, :phone, :salesforce_id
  validates :phone, length: { is: 10 }
  validates :salesforce_id, length: { is: 7 }

  validates_uniqueness_of :salesforce_id
  validates_associated :goals
  validates_associated :messages

  belongs_to :user
  has_many :goals
  has_many :messages
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @goals = @client.goals
  end

  # GET /clients/new
  def new
    @user = User.find(params[:user_id])
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.user_id = params[:user_id]

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :phone, :salesforce_id)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client, :html => {:class => 'pure-form pure-form-stacked'}) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :salesforce_id %>
    <%= f.text_field :salesforce_id %>
  </div>
  <% if @user %>
    <%= hidden_field_tag :user_id, @user.id %>
  <% end %>
  <div >
    <%= f.submit "Submit",:class => 'actions pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Update Client Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', client_path(@client) %>

app/views/clients/index.html.erb
  <div class="test">
  <div class="intro inside">
    <h1>
      Welcome, coach!
    </h1> 
  </div>
  <div class="intro inside">
    <button class="pure-button pure-button-primary">
      <%= link_to 'New Client', new_client_path %>
    </button>
  </div>
  </div>
  <div class="inside">
<h1>Listing clients</h1>
<table class="pure-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Salesforce</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.phone %></td>
        <td><%= client.salesforce_id %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<div class="inside">
  <h1>New client</h1>

  <%= render 'form' %>

  <%= link_to 'Back', user_path(@user) %>
</div>

app/views/clients/show.html.erb
<div class="inside">
<h1> Client Details</h1>
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @client.name %>
	</p>

	<p>
	  <strong>Phone:</strong>
	  <%= @client.phone %>
	</p>

	<p>
	  <strong>Salesforce:</strong>
	  <%= @client.salesforce_id %>
	</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', user_path(@client.user) %>

	<h2>Goals</h2>

	<ol>
	<% @goals.each do |goal| %>
	    <li><%= render partial: 'shared/client_goal_list_item', locals: {goal: goal} %></li>
	<% end %>
	</ol>
	 <button class="pure-button pure-button-primary"><%= link_to "New Goal", "/clients/#{@client.id}/goals/new" %></button>

</div>