config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about'
  get 'welcome/dashboard'
  root :to => 'welcome#index'

  get '/users/:user_id/clients/new', :to => 'clients#new'

  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'devise/registrations#new'}

  get '/clients/:client_id/goals/new', :to => 'goals#new'
  get '/goals/:goal_id/steps/new', :to => 'steps#new'
  get '/steps/:step_id/messages/new', :to => 'messages#new'

  resources :clients
  resources :goals
  resources :steps
  resources :messages

end

app/models/step.rb
class Step < ActiveRecord::Base
  validates_presence_of :content, :status, :by_when
  validates_associated :messages

  belongs_to :goal
  has_many :messages
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:show, :edit, :update, :destroy]

  # GET /steps
  # GET /steps.json
  def index
    @steps = Step.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @messages = @step.messages
  end

  # GET /steps/new
  def new
    p params
    @goal = Goal.find(params[:goal_id])
    @step = Step.new
  end

  # GET /steps/1/edit
  def edit
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = Step.new(step_params)
    @step.goal_id = params[:goal_id]
    respond_to do |format|
      if @step.save
        format.html { redirect_to @step, notice: 'Step was successfully created.' }
        format.partial { render partial:"shared/goal_step_list_item", :formats => ['html'], locals: {step: @step}}
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /steps/1
  # PATCH/PUT /steps/1.json
  def update
    respond_to do |format|
      if @step.update(step_params)
        format.html { redirect_to @step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @step }
      else
        format.html { render :edit }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step.destroy
    respond_to do |format|
      format.html { redirect_to steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step
      @step = Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:content, :status, :by_when, :goal_id)
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_for(@step, remote: true, :format => :partial, :html => {:class => 'pure-form'}) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <br>
  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <br>
  <div class="field">
    <%= f.label :by_when %>
    <%= f.date_select :by_when %>
  </div>
  <br>
  <% if @goal %>
    <%= hidden_field_tag(:goal_id, @goal.id) %>
  <% end %>
  <div class="actions">
    <%= f.submit "Submit",:class => 'actions pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', step_path(@step) %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Status</th>
      <th>By when</th>
      <th>Goal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.content %></td>
        <td><%= step.status %></td>
        <td><%= step.by_when %></td>
        <td><%= step.goal %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', goal_path(@goal) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @step.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @step.status %>
</p>

<p>
  <strong>By when:</strong>
  <%= @step.by_when %>
</p>

<p>
  <strong>Goal:</strong>
  <%= link_to "View Goal", goal_path(@step.goal_id) %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %>
<%= link_to 'Back', goal_path(@step.goal_id) %>

<ol>
  <% @messages.each do |message| %>
      <li><%= render partial: 'shared/step_message_list_item', locals: {message: message} %></li>
  <% end %>
</ol>

<%= link_to "New Message", "/steps/#{@step.id}/messages/new" %>