config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about'
  get 'welcome/dashboard'
  root :to => 'welcome#index'

  get '/users/:user_id/clients/new', :to => 'clients#new'

  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'devise/registrations#new'}

  get '/clients/:client_id/goals/new', :to => 'goals#new'
  get '/goals/:goal_id/steps/new', :to => 'steps#new'
  get '/steps/:step_id/messages/new', :to => 'messages#new'

  resources :clients
  resources :goals
  resources :steps
  resources :messages

end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates_presence_of :content, :category

  has_many :steps
  belongs_to :client
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
    @steps = @goal.steps
    @step = Step.new
  end

  # GET /goals/new
  def new
    @client = Client.find(params[:client_id])
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    @goal.client_id = params[:client_id]

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:content, :category, :num_value, :client_id)
    end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/_form.html.erb
<%= form_for(@goal, :html => {:class => 'pure-form pure-form-stacked'}) do |f| %>
  <% if @goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
      <% @goal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>
  <% if @client %>
    <%= hidden_field_tag :client_id, @client.id %>
  <% end %>

  <div class="actions">
    <%= f.submit "Submit",:class => 'actions pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing goal</h1>

<%= render 'form' %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goal_path(@goal) %>

app/views/goals/index.html.erb
<h1>Listing goals</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Category</th>
      <th>Num value</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.content %></td>
        <td><%= goal.category %></td>
        <td><%= goal.num_value %></td>
        <td><%= goal.client %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<div class="inside">
<h1>New Goal</h1>

<%= render 'form' %>

<%= link_to 'Back', client_path(@client) %>
</div>

app/views/goals/show.html.erb
<div class="inside">
  <h1>
  Client Goals
</h1>
<p id="notice"><%= notice %></p>

<h1>Goal Details</h1>

<p>
  <strong>Goal Description:</strong>
  <%= @goal.content %>
</p>

<p>
  <strong>Goal Type:</strong>
  <%= @goal.category %>
</p>
<p>
  <strong>Client:</strong>
  <%= link_to "#{@goal.client.name}", client_path(@goal.client_id) %>
</p>

<h2>Steps</h2>

<ol id="steps-list">
  <% @steps.each do |step| %>
    <li><%= render partial: 'shared/goal_step_list_item', locals: { step:step } %></li>
  <% end %>
</ol>

<button class="pure-button pure-button-primary">
<%= link_to "New Step", "/#",   :id => 'new-step-link' %></button>
<%= render partial: 'steps/form', locals: {step: @step, goal: @goal} %>

<br>
<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', client_path(@goal.client_id) %>

<script type="text/javascript">
    $('#new_step').hide();
    $('#new-step-link').click(function(e) {
      e.preventDefault();
      $('#new_step').toggle();
      return false;
    });
    $('#new_step').bind('ajax:success', function(e, response) {
      $("#steps-list").append('<li>'+response+'</li>');
      $("#new_step").hide();
      $("#new_step")[0].reset();
    });
</script>

</div>